export const LAST_RAFFLES_AMOUNT = 31;

export const MIN_DELAY_BETWEEN_RAFFLES = 1;
export const MAX_DELAY_BETWEEN_RAFFLES = 4;

export const MIN_DELAY_BETWEEN_TWITTERS = 4;
export const MAX_DELAY_BETWEEN_TWITTERS = 8;

